package org.bolivia.game;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import java.applet.AudioClip;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @web http://www.jc-mouse.net/
 * @author Mouse
 */
public class Juego extends javax.swing.JFrame {
    protected DataOutputStream dos;
    protected DataInputStream dis;
    protected Socket sk;
    JFigura jfa = new JFigura();
    JFigura jfb = new JFigura();
    JFigura jfc = new JFigura();
    public static String usr = "";
    static String pass = "";
    static String IP = "";
    static String bolsa = "";
    AudioClip sonido2;
    /**
     * Creates new form Juego
     */
    public Juego() {
        
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setTitle("Casino Pokémon");
        
        jFigA.add(jfa);
        jFigB.add(jfb);
        jFigC.add(jfc);
        
            sonido2 = java.applet.Applet.newAudioClip(getClass().getResource("/org/bolivia/game/res/slot.wav"));
        lbEstado.setText("");
      
        repaint();
    }
            
    void getUsrPass(String usuario, String contra, String ip, String bolsaTotal){
        this.usr = usuario;
        this.pass = contra;
        this.IP = ip;
        this.bolsa = bolsaTotal;
        this.bolsaTotal.setText(bolsa);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jFigA = new javax.swing.JPanel();
        jFigB = new javax.swing.JPanel();
        jFigC = new javax.swing.JPanel();
        lbEstado = new javax.swing.JLabel();
        lbCredito = new javax.swing.JTextField();
        lbApuesta = new javax.swing.JTextField();
        lbBoton = new javax.swing.JLabel();
        bolsaTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/bgt.jpg"))); // NOI18N
        jcMousePanel1.setPreferredSize(new java.awt.Dimension(700, 400));
        jcMousePanel1.setVisibleLogo(false);

        javax.swing.GroupLayout jFigALayout = new javax.swing.GroupLayout(jFigA);
        jFigA.setLayout(jFigALayout);
        jFigALayout.setHorizontalGroup(
            jFigALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigALayout.setVerticalGroup(
            jFigALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFigBLayout = new javax.swing.GroupLayout(jFigB);
        jFigB.setLayout(jFigBLayout);
        jFigBLayout.setHorizontalGroup(
            jFigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigBLayout.setVerticalGroup(
            jFigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFigCLayout = new javax.swing.GroupLayout(jFigC);
        jFigC.setLayout(jFigCLayout);
        jFigCLayout.setHorizontalGroup(
            jFigCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigCLayout.setVerticalGroup(
            jFigCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lbEstado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(255, 255, 0));
        lbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado.setText("jLabel1");

        lbCredito.setBackground(new java.awt.Color(0, 0, 0));
        lbCredito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCredito.setForeground(new java.awt.Color(255, 0, 0));
        lbCredito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbCredito.setText("1000");
        lbCredito.setCaretColor(new java.awt.Color(204, 0, 0));
        lbCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lbCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbCreditoKeyTyped(evt);
            }
        });

        lbApuesta.setBackground(new java.awt.Color(0, 0, 0));
        lbApuesta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbApuesta.setForeground(new java.awt.Color(255, 0, 0));
        lbApuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbApuesta.setText("100");
        lbApuesta.setCaretColor(new java.awt.Color(153, 0, 0));
        lbApuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbApuestaKeyTyped(evt);
            }
        });

        lbBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/boton.jpg"))); // NOI18N
        lbBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbBoton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/boton.jpg"))); // NOI18N
        lbBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBotonMouseClicked(evt);
            }
        });

        bolsaTotal.setEditable(false);
        bolsaTotal.setBackground(new java.awt.Color(0, 0, 0));
        bolsaTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bolsaTotal.setForeground(new java.awt.Color(255, 0, 0));
        bolsaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jFigA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jFigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jFigC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBoton)
                            .addComponent(lbCredito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbApuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bolsaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bolsaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lbCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFigA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFigC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(lbBoton)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbEstado)
                        .addGap(83, 83, 83))))
        );

        getContentPane().add(jcMousePanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBotonMouseClicked
        lbEstado.setText("");
       
        
        //sonido.loop();
        try{
        if(lbCredito.getText().isEmpty() || lbApuesta.getText().isEmpty()){
       JOptionPane.showMessageDialog(this, "¡Crédito o apuesta no pueden estar vacíos!");
            lbCredito.setText("");
            lbCredito.requestFocus();
      }else{
            if( (Integer.parseInt(lbApuesta.getText()) <= Integer.parseInt(lbCredito.getText())) && Integer.parseInt(lbCredito.getText()) > 0)
        {
            //lbBoton.setEnabled(false);
            /*AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/org/bolivia/game/res/poke.wav"));
            sonido.play();*/
            bolsaTotal.setText(this.bolsa);
            if(Integer.parseInt(lbCredito.getText())<= Integer.parseInt(this.bolsa)){
               /* try {
                    Thread.sleep(1500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            sonido.stop();*/
            
            
            sonido2.play();
            sonido2.loop();
            
            PlayWorker pwA = new PlayWorker(jfa);
            pwA.execute();

            PlayWorker pwB = new PlayWorker(jfb);
            pwB.execute();

            PlayWorker pwC = new PlayWorker(jfc);
            pwC.execute();
            //Aqui poner validación
            
            CheckWorker cw = new CheckWorker(pwA,pwB,pwC,lbEstado,lbCredito,lbApuesta, bolsaTotal, lbBoton);
            
            cw.execute();
            //sonido2.stop();
           
            }else{
                JOptionPane.showMessageDialog(this, "El crédito no puede ser mayor a la bolsa total");
                lbCredito.setText("");
                lbCredito.requestFocus();
            }
           // bolsaTotal.setText(this.bolsa);
        }else{
            JOptionPane.showMessageDialog(this, "¡Crédito insuficiente!");
            lbCredito.setText("");
            lbCredito.requestFocus();
        }
            
        }
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(this, "Sólo se aceptan números.");
            lbCredito.setText("");
            lbCredito.requestFocus();
        }
            
    }//GEN-LAST:event_lbBotonMouseClicked

    private void lbCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbCreditoKeyTyped
        char c = evt.getKeyChar();
        int enter = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
        if(lbCredito.getText().length()>=6) evt.consume();
        if(enter == 10){
            if(lbCredito.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No puede dejar el campo vacío");
                lbCredito.requestFocus();
            }else
            lbApuesta.requestFocus();
        }
    }//GEN-LAST:event_lbCreditoKeyTyped

    private void lbApuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbApuestaKeyTyped
        char c = evt.getKeyChar();
        int enter = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
        if(lbApuesta.getText().length()>=6) evt.consume();
        if(enter == 10){
            if(lbApuesta.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No puede dejar el campo vacío");
                lbApuesta.requestFocus();
            }else
            lbApuesta.requestFocus();
        }
    }//GEN-LAST:event_lbApuestaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Login().setVisible(true);
                
                new Juego().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bolsaTotal;
    private javax.swing.JPanel jFigA;
    private javax.swing.JPanel jFigB;
    private javax.swing.JPanel jFigC;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTextField lbApuesta;
    private javax.swing.JLabel lbBoton;
    private javax.swing.JTextField lbCredito;
    private javax.swing.JLabel lbEstado;
    // End of variables declaration//GEN-END:variables
}
