/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Test */

#ifndef _Included_test_Test
#define _Included_test_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Test
 * Method:    getDouble
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Test_getDouble
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
